services:
  - type: web
    name: seps-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: BREVO_SMTP_HOST
        value: smtp-relay.brevo.com
      - key: BREVO_SMTP_PORT
        value: "587"
      - key: BREVO_SMTP_USER
        sync: false
      - key: BREVO_SMTP_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_NAME
        value: "SEPS SRM"
      - key: PROJECT_NAME
        value: "SEPS SRM"
