// Frontend/src/utils/reportExportUtils.js
import * as XLSX from "xlsx";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Exports the Central Statistics and Allocation Report to a multi-sheet Microsoft Excel (.xlsx) file.
 *
 * @param {Object} params
 * @param {Object} params.stats - Complete stats object from backend /api/statistics
 * @param {Object} params.user - Current logged-in coordinator user object
 * @param {string} params.selectedDomain - Currently selected domain filter ("all" or domain name)
 * @param {"all"|"filtered"} params.scope - Whether to export "all" or "filtered" domain view
 * @returns {{ fileName: string, teamCount: number }}
 */
export function exportReportToExcel({ stats, user, selectedDomain = "all", scope = "all" }) {
  if (!stats) throw new Error("No statistics data available to export.");

  const isFiltered = scope === "filtered" && selectedDomain !== "all";
  const effectiveDomain = isFiltered ? selectedDomain : "All Research Domains";

  const targetGroups = isFiltered
    ? (stats.groupDetails || []).filter(
        (g) => (g.domain || "").toLowerCase() === selectedDomain.toLowerCase()
      )
    : (stats.groupDetails || []);

  const wb = XLSX.utils.book_new();

  // ----------------------------------------------------
  // 1. Sheet: Executive Summary & Department Overview
  // ----------------------------------------------------
  const summaryData = [
    ["SRM INSTITUTE OF SCIENCE AND TECHNOLOGY"],
    ["Department of Electronics and Communication Engineering (ECE)"],
    ["SEPS 2.0 - Central Project Allocation & Institutional Statistics Report"],
    [],
    ["REPORT METADATA", ""],
    ["Report Generation Date & Time:", new Date().toLocaleString("en-IN")],
    ["Generated By (Coordinator):", `${user?.fullName || "Admin Coordinator"} (${user?.email || "N/A"})`],
    ["Report Filter Scope:", effectiveDomain],
    ["Active Filter Status:", isFiltered ? `Domain Filter Applied: ${selectedDomain}` : "Unfiltered (Entire Department Cohort)"],
    ["Confidentiality Classification:", "Official Academic Institutional Record - Internal Use Only"],
    [],
    ["INSTITUTIONAL CYCLE KEY PERFORMANCE INDICATORS (KPIS)", "COUNT", "DESCRIPTION"],
    ["Total Faculty Guides Registered", stats.teacherCount || 0, "Total registered faculty accounts in department"],
    ["Total Students Registered", stats.studentCount || 0, "Total enrolled students eligible for major project"],
    ["Total Project Topics Proposed", stats.projectCount || 0, "Total project proposals uploaded by faculty guides"],
    ["Total Applications Submitted", stats.applicationCount || 0, "Total student applications (Team + Individual)"],
    ["Approved Student Groups / Teams", stats.groupCount || 0, "Approved multi-member student team allocations"],
    ["Approved Individual Allocations", stats.individualCount || 0, "Approved single-student project allocations"],
    ["Faculty With Uploaded Proposals", stats.teachersWithProjects?.length || 0, "Active faculty with uploaded proposals"],
    ["Faculty Without Proposals (Pending)", stats.teachersWithoutProjects?.length || 0, "Faculty with no uploaded proposals yet"],
    ["Students With Application / Allocation", stats.studentsWithApplications?.length || 0, "Students successfully applied or allocated"],
    ["Students Without Application (Pending)", stats.studentsWithoutApplications?.length || 0, "Students with no application recorded yet"],
    [],
    ["RESEARCH DOMAIN TOPIC DISTRIBUTION", "TOPICS PROPOSED", "% OF TOTAL TOPICS", "ALLOCATED TEAMS IN DOMAIN"],
  ];

  if (stats.domainCounts) {
    const totalTopics = stats.projectCount || 1;
    Object.entries(stats.domainCounts).forEach(([domain, count]) => {
      const allocatedInDomain = (stats.groupDetails || []).filter(
        (g) => (g.domain || "").toLowerCase() === domain.toLowerCase()
      ).length;
      const pct = ((count / totalTopics) * 100).toFixed(1) + "%";
      summaryData.push([domain, count, pct, allocatedInDomain]);
    });
  }

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
  wsSummary["!cols"] = [{ wch: 42 }, { wch: 20 }, { wch: 48 }, { wch: 30 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, "Executive Summary");

  // ----------------------------------------------------
  // 2. Sheet: Allocated Student Teams & Topics
  // ----------------------------------------------------
  const teamsHeader = [
    "S.No.",
    "Project Title",
    "Research Domain",
    "Faculty Guide",
    "Team Size",
    "Student 1 Name",
    "Student 1 Reg No",
    "Student 2 Name",
    "Student 2 Reg No",
    "Student 3 Name",
    "Student 3 Reg No",
    "All Members (Summary)",
  ];

  const teamsRows = targetGroups.map((g, idx) => {
    const s1 = g.students?.[0] || {};
    const s2 = g.students?.[1] || {};
    const s3 = g.students?.[2] || {};
    const summary = (g.students || [])
      .map((st, i) => `${i + 1}. ${st.name} (${st.regNo})`)
      .join("; ");
    return [
      idx + 1,
      g.projectTitle || "Untitled Project",
      g.domain || "General",
      g.teacherName || "Unassigned",
      g.students?.length || 0,
      s1.name || "",
      s1.regNo || "",
      s2.name || "",
      s2.regNo || "",
      s3.name || "",
      s3.regNo || "",
      summary,
    ];
  });

  const wsTeams = XLSX.utils.aoa_to_sheet([teamsHeader, ...teamsRows]);
  wsTeams["!cols"] = [
    { wch: 8 },
    { wch: 45 },
    { wch: 32 },
    { wch: 28 },
    { wch: 12 },
    { wch: 24 },
    { wch: 20 },
    { wch: 24 },
    { wch: 20 },
    { wch: 24 },
    { wch: 20 },
    { wch: 48 },
  ];
  const teamsSheetName = isFiltered ? "Allocated Teams (Filtered)" : "Allocated Teams";
  XLSX.utils.book_append_sheet(wb, wsTeams, teamsSheetName);

  // ----------------------------------------------------
  // 3. Sheet: Faculty Participation & Proposal Status
  // ----------------------------------------------------
  const facultyHeader = [
    "S.No.",
    "Faculty Guide Name",
    "Official Email",
    "Proposals Count",
    "Submission Status",
    "Proposed Project Titles",
  ];

  const activeTeachers = (stats.teachersWithProjects || []).map((t, idx) => [
    idx + 1,
    t.name,
    t.email,
    t.projects?.length || 0,
    "Active - Topics Uploaded",
    (t.projects || []).join(" | "),
  ]);

  const pendingTeachers = (stats.teachersWithoutProjects || []).map((t, idx) => [
    activeTeachers.length + idx + 1,
    t.name,
    t.email,
    0,
    "Pending - No Topics Uploaded",
    "None",
  ]);

  const wsFaculty = XLSX.utils.aoa_to_sheet([facultyHeader, ...activeTeachers, ...pendingTeachers]);
  wsFaculty["!cols"] = [
    { wch: 8 },
    { wch: 28 },
    { wch: 34 },
    { wch: 18 },
    { wch: 30 },
    { wch: 65 },
  ];
  XLSX.utils.book_append_sheet(wb, wsFaculty, "Faculty Status");

  // ----------------------------------------------------
  // 4. Sheet: Pending Students (Action Required)
  // ----------------------------------------------------
  const pendingStudentsHeader = [
    "S.No.",
    "Student Name",
    "Official Email",
    "Registration Number",
    "Current Status",
    "Action Required",
  ];

  const pendingStudentsRows = (stats.studentsWithoutApplications || []).map((s, idx) => [
    idx + 1,
    s.name,
    s.email,
    s.regNo,
    "Unallocated / No Application",
    "Follow up for project submission / team formation",
  ]);

  const wsPendingStudents = XLSX.utils.aoa_to_sheet([
    pendingStudentsHeader,
    ...pendingStudentsRows,
  ]);
  wsPendingStudents["!cols"] = [
    { wch: 8 },
    { wch: 28 },
    { wch: 34 },
    { wch: 22 },
    { wch: 30 },
    { wch: 48 },
  ];
  XLSX.utils.book_append_sheet(wb, wsPendingStudents, "Pending Students");

  // ----------------------------------------------------
  // 5. If filtered, append All Allocated Teams as reference sheet
  // ----------------------------------------------------
  if (isFiltered) {
    const allTeamsRows = (stats.groupDetails || []).map((g, idx) => {
      const s1 = g.students?.[0] || {};
      const s2 = g.students?.[1] || {};
      const s3 = g.students?.[2] || {};
      const summary = (g.students || [])
        .map((st, i) => `${i + 1}. ${st.name} (${st.regNo})`)
        .join("; ");
      return [
        idx + 1,
        g.projectTitle || "Untitled Project",
        g.domain || "General",
        g.teacherName || "Unassigned",
        g.students?.length || 0,
        s1.name || "",
        s1.regNo || "",
        s2.name || "",
        s2.regNo || "",
        s3.name || "",
        s3.regNo || "",
        summary,
      ];
    });
    const wsAllTeams = XLSX.utils.aoa_to_sheet([teamsHeader, ...allTeamsRows]);
    wsAllTeams["!cols"] = wsTeams["!cols"];
    XLSX.utils.book_append_sheet(wb, wsAllTeams, "All Allocated Teams");
  }

  // Generate File & Trigger Browser Download
  const dateStr = new Date().toISOString().slice(0, 10);
  const domainSlug = isFiltered ? `_${selectedDomain.replace(/[^a-zA-Z0-9]/g, "_")}` : "_All_Domains";
  const fileName = `SEPS_Allocation_Report${domainSlug}_${dateStr}.xlsx`;

  XLSX.writeFile(wb, fileName);
  return { fileName, teamCount: targetGroups.length };
}

/**
 * Exports the Central Statistics and Allocation Report to a high-fidelity, landscape-oriented PDF.
 *
 * @param {Object} params
 * @param {Object} params.stats - Complete stats object from backend /api/statistics
 * @param {Object} params.user - Current logged-in coordinator user object
 * @param {string} params.selectedDomain - Currently selected domain filter ("all" or domain name)
 * @param {"all"|"filtered"} params.scope - Whether to export "all" or "filtered" domain view
 * @returns {{ fileName: string, teamCount: number, totalPages: number }}
 */
export function exportReportToPDF({ stats, user, selectedDomain = "all", scope = "all" }) {
  if (!stats) throw new Error("No statistics data available to export.");

  const isFiltered = scope === "filtered" && selectedDomain !== "all";
  const effectiveDomain = isFiltered ? selectedDomain : "All Research Domains";

  const targetGroups = isFiltered
    ? (stats.groupDetails || []).filter(
        (g) => (g.domain || "").toLowerCase() === selectedDomain.toLowerCase()
      )
    : (stats.groupDetails || []);

  const doc = new jsPDF("l", "mm", "a4"); // Landscape A4 (297 x 210 mm)
  const pageWidth = doc.internal.pageSize.getWidth(); // 297 mm
  const pageHeight = doc.internal.pageSize.getHeight(); // 210 mm
  const marginX = 14;
  const contentWidth = pageWidth - marginX * 2; // 269 mm

  // Helper function to draw the official header banner
  const drawOfficialHeader = (startY = 10) => {
    // Top primary accent bar
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(marginX, startY, contentWidth, 3.5, "F");

    // Cyan secondary bar
    doc.setFillColor(8, 145, 178); // cyan-600
    doc.rect(marginX, startY + 3.5, contentWidth, 1.2, "F");

    let y = startY + 9.5;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text("SRM INSTITUTE OF SCIENCE AND TECHNOLOGY", marginX, y);

    y += 5;
    doc.setFontSize(9.5);
    doc.setTextColor(71, 85, 105); // slate-600
    doc.text("Department of Electronics and Communication Engineering (ECE)", marginX, y);

    y += 4.5;
    doc.setFontSize(8.5);
    doc.setTextColor(8, 145, 178); // cyan-600
    doc.text("SEPS 2.0 - Student Early Project Allocation System", marginX, y);

    y += 5.5;
    doc.setFontSize(11);
    doc.setTextColor(15, 23, 42);
    doc.text("CENTRAL ALLOCATION & INSTITUTIONAL STATISTICS REPORT", marginX, y);

    // Metadata card on the right
    const metaX = marginX + 160;
    const metaY = startY + 6.5;
    const metaW = contentWidth - 160;
    const metaH = 20;

    doc.setFillColor(248, 250, 252); // slate-50
    doc.setDrawColor(203, 213, 225); // slate-300
    doc.roundedRect(metaX, metaY, metaW, metaH, 2, 2, "FD");

    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(100, 116, 139);
    doc.text("REPORT METADATA & SCOPE", metaX + 4, metaY + 4.5);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(30, 41, 59);
    doc.text(`Generated: ${new Date().toLocaleString("en-IN")}`, metaX + 4, metaY + 8.5);
    doc.text(`By: ${user?.fullName || "Admin Coordinator"} (${user?.email || "N/A"})`, metaX + 4, metaY + 12.5);

    doc.setFont("helvetica", "bold");
    doc.setTextColor(isFiltered ? 8 : 30, isFiltered ? 145 : 41, isFiltered ? 178 : 59);
    const scopeLabel = `Scope: ${effectiveDomain}`;
    // Truncate if too long for box
    const displayScope = scopeLabel.length > 42 ? scopeLabel.substring(0, 39) + "..." : scopeLabel;
    doc.text(displayScope, metaX + 4, metaY + 16.5);

    return y + 6;
  };

  // 1. Draw Header on Page 1
  let currentY = drawOfficialHeader(10);

  // Section 1: KPI Metrics Grid
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(15, 23, 42);
  doc.text("1. Institutional Cycle Key Performance Indicators", marginX, currentY);
  currentY += 2.5;

  autoTable(doc, {
    startY: currentY,
    margin: { left: marginX, right: marginX },
    tableWidth: contentWidth,
    head: [
      [
        "Faculty Guides",
        "Registered Students",
        "Topics Proposed",
        "Total Applications",
        "Approved Groups",
        "Approved Indiv.",
        "Active Faculty",
        "Pending Students",
      ],
    ],
    body: [
      [
        String(stats.teacherCount || 0),
        String(stats.studentCount || 0),
        String(stats.projectCount || 0),
        String(stats.applicationCount || 0),
        String(stats.groupCount || 0),
        String(stats.individualCount || 0),
        String(stats.teachersWithProjects?.length || 0),
        String(stats.studentsWithoutApplications?.length || 0),
      ],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontSize: 7.5,
      fontStyle: "bold",
      halign: "center",
      cellPadding: 1.8,
    },
    bodyStyles: {
      fontSize: 10.5,
      fontStyle: "bold",
      halign: "center",
      textColor: [8, 145, 178],
      fillColor: [240, 249, 255],
      cellPadding: 2.5,
    },
    columnStyles: {
      0: { cellWidth: 33 },
      1: { cellWidth: 33 },
      2: { cellWidth: 33 },
      3: { cellWidth: 33 },
      4: { cellWidth: 33 },
      5: { cellWidth: 33 },
      6: { cellWidth: 34 },
      7: { cellWidth: 37 },
    },
    tableLineColor: [203, 213, 225],
    tableLineWidth: 0.2,
  });

  currentY = doc.lastAutoTable.finalY + 7;

  // Section 2: Research Domain Topic Distribution
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9.5);
  doc.setTextColor(15, 23, 42);
  doc.text("2. Research Domain Distribution & Topic Allocation Status", marginX, currentY);
  currentY += 2.5;

  const totalTopics = stats.projectCount || 1;
  const domainRows = stats.domainCounts
    ? Object.entries(stats.domainCounts).map(([dom, count], idx) => {
        const allocatedInDom = (stats.groupDetails || []).filter(
          (g) => (g.domain || "").toLowerCase() === dom.toLowerCase()
        ).length;
        const pct = ((count / totalTopics) * 100).toFixed(1) + "%";
        return [idx + 1, dom, count, pct, allocatedInDom];
      })
    : [["-", "No domain data available", 0, "0%", 0]];

  autoTable(doc, {
    startY: currentY,
    margin: { left: marginX, right: marginX },
    tableWidth: contentWidth,
    head: [["#", "Research Domain", "Topics Proposed", "% of Total Topics", "Allocated Teams in Domain"]],
    body: domainRows,
    theme: "striped",
    headStyles: {
      fillColor: [8, 145, 178], // cyan-600
      textColor: [255, 255, 255],
      fontSize: 7.5,
      fontStyle: "bold",
      cellPadding: 2,
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [30, 41, 59],
      cellPadding: 1.8,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 119, fontStyle: "bold" },
      2: { cellWidth: 40, halign: "center" },
      3: { cellWidth: 40, halign: "center" },
      4: { cellWidth: 60, halign: "center" },
    },
    tableLineColor: [226, 232, 240],
    tableLineWidth: 0.15,
  });

  // Section 3: Allocated Student Teams & Topics (Start on new page)
  doc.addPage();
  currentY = 14;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.setTextColor(15, 23, 42);
  const teamSectionTitle = isFiltered
    ? `3. Approved Student Teams & Allocated Topics - Filtered: ${selectedDomain} (${targetGroups.length} Teams)`
    : `3. Approved Student Teams & Allocated Topics - Entire Department (${targetGroups.length} Teams)`;
  doc.text(teamSectionTitle, marginX, currentY);
  currentY += 4;

  const teamTableBody =
    targetGroups.length === 0
      ? [["-", "No allocated teams found matching this scope.", "-", "-", "-"]]
      : targetGroups.map((g, idx) => {
          const formattedMembers = (g.students || [])
            .map((st, i) => `${i + 1}. ${st.name} (${st.regNo})`)
            .join("\n");
          return [
            idx + 1,
            g.projectTitle || "Untitled Project",
            g.domain || "General",
            g.teacherName || "Unassigned",
            formattedMembers || "No students listed",
          ];
        });

  autoTable(doc, {
    startY: currentY,
    margin: { left: marginX, right: marginX },
    head: [["#", "Project Title", "Research Domain", "Faculty Guide", "Allocated Team Members"]],
    body: teamTableBody,
    showHead: "everyPage",
    theme: "striped",
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: "bold",
      cellPadding: 2.2,
    },
    bodyStyles: {
      fontSize: 7.5,
      textColor: [30, 41, 59],
      cellPadding: 2.2,
      valign: "middle",
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      1: { cellWidth: 80, fontStyle: "bold" },
      2: { cellWidth: 48 },
      3: { cellWidth: 46, fontStyle: "bold" },
      4: { cellWidth: 85 },
    },
    tableLineColor: [226, 232, 240],
    tableLineWidth: 0.15,
  });

  // Section 4: Faculty Guide Contributions
  const facultyList = stats.teachersWithProjects || [];
  if (facultyList.length > 0) {
    doc.addPage();
    currentY = 14;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10.5);
    doc.setTextColor(15, 23, 42);
    doc.text(`4. Faculty Guide Contributions (${facultyList.length} Active Guides)`, marginX, currentY);
    currentY += 4;

    const facultyRows = facultyList.map((t, idx) => [
      idx + 1,
      t.name,
      t.email,
      t.projects?.length || 0,
      (t.projects || []).join("\n"),
    ]);

    autoTable(doc, {
      startY: currentY,
      margin: { left: marginX, right: marginX },
      head: [["#", "Faculty Name", "Official Email", "Topics Uploaded", "Proposed Topics List"]],
      body: facultyRows,
      showHead: "everyPage",
      theme: "striped",
      headStyles: {
        fillColor: [15, 23, 42],
        textColor: [255, 255, 255],
        fontSize: 8,
        fontStyle: "bold",
        cellPadding: 2.2,
      },
      bodyStyles: {
        fontSize: 7.5,
        textColor: [30, 41, 59],
        cellPadding: 2.2,
        valign: "middle",
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      columnStyles: {
        0: { cellWidth: 10, halign: "center" },
        1: { cellWidth: 50, fontStyle: "bold" },
        2: { cellWidth: 55 },
        3: { cellWidth: 26, halign: "center" },
        4: { cellWidth: 128 },
      },
      tableLineColor: [226, 232, 240],
      tableLineWidth: 0.15,
    });
  }

  // Footer: Add Page Numbers & Confidentiality watermark on EVERY page
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const footerY = pageHeight - 9;

    // Divider line
    doc.setDrawColor(203, 213, 225); // slate-300
    doc.setLineWidth(0.3);
    doc.line(marginX, footerY - 2, pageWidth - marginX, footerY - 2);

    // Left footer text
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 116, 139);
    doc.text(
      "SEPS 2.0 Academic Portal | Department of ECE, SRMIST | Official Confidential Academic Report",
      marginX,
      footerY + 2
    );

    // Right footer text (Page X of Y)
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(15, 23, 42);
    const pageStr = `Page ${i} of ${totalPages}`;
    doc.text(pageStr, pageWidth - marginX - doc.getTextWidth(pageStr), footerY + 2);
  }

  // Save File
  const dateStr = new Date().toISOString().slice(0, 10);
  const domainSlug = isFiltered ? `_${selectedDomain.replace(/[^a-zA-Z0-9]/g, "_")}` : "_All_Domains";
  const fileName = `SEPS_Allocation_Report${domainSlug}_${dateStr}.pdf`;

  doc.save(fileName);
  return { fileName, teamCount: targetGroups.length, totalPages };
}
